### PR TITLE
Apply changes necessary for Python 2.6 support

### PR DESCRIPTION
**Pull request by rvdh**

### CODE REVIEW

**Comment by styxit** [comment]
I would recommend to use one style for variable names. Instead of using things like `isfile`, use `is_file` or `isFile` (probably the first).

Maybe determine what format to use for all projects. Check with @robinmulder

I spotted af few, but there could be more.
- rawinput
- adminuser
- adminpass
- starttls
- mockinit
- mockconnect
- mockdict
- mockchown
- mockimapssl
- statreturn
- getreturn

**Comment by robinmulder** [comment]
I think underscores is pretty much standard in Python code, so let's use that.

**Comment by robinmulder** [comment]
Is there also a way to let the mysql-pyton installation look for headers and binaries in /usr/local/mysql? This is the default on servers with DirectAdmin so the setup will always fail without manually configuring this. You can pass this as a pip option but not sure how it works with setuptools.

**Comment by robinmulder** [comment]
:+1: ship it

**Pull request merged**
